// Single source of truth for all clan ranks, ordered lowest → highest
const CLAN_RANKS = [
  'Magic',
  'Crusader',
  'Coordinator',
  'gnome_child',
  'Templar',
  'beast',
  'competitor',
  'protector',
  'deputy_owner',
  'Owner',
  'diamond',
  'epic',
  'gold',
  'zenyte',
  'Recruit',
  'Corporal',
  'Sergeant',
  'Lieutenant',
  'Captain',
  'General',
  'Master',
  'Officer',
  'Commander',
  'Colonel',
  'Brigadier',
  'Admiral',
  'Marshal',
];

const RANK_COLORS = {
  Magic:        0x9b59b6,
  Crusader:     0xe74c3c,
  Coordinator:  0x3498db,
  gnome_child:  0x2ecc71,
  Templar:      0xf1c40f,
  beast:        0xe67e22,
  competitor:   0x95a5a6,
  protector:    0x1abc9c,
  deputy_owner: 0xc0392b,
  Owner:        0xf1c40f,
  diamond:      0x85c1e9,
  epic:         0x8e44ad,
  gold:         0xf39c12,
  zenyte:       0xe74c3c,
  Recruit:      0x808080,
  Corporal:     0x3498db,
  Sergeant:     0x2ecc71,
  Lieutenant:   0xe67e22,
  Captain:      0xe74c3c,
  General:      0xf1c40f,
  Master:       0x9b59b6,
  Officer:      0x1abc9c,
  Commander:    0xc0392b,
  Colonel:      0x8e44ad,
  Brigadier:    0xf39c12,
  Admiral:      0x2980b9,
  Marshal:      0xc8a951,
};

function rankColor(rank) {
  return RANK_COLORS[rank] ?? 0xc8a951;
}

module.exports = { CLAN_RANKS, rankColor };
